### ISSUE TITLE
"Check for updates" not working

### ISSUE THREAD

**Issue by cyberphobie** [Kalejin/DCSB#10]
When clicking on Help > Check for updates, an error occurs.

**What should happen:**
Program checks for available updates.

**What happens:**
An error message pops up reading: "The file or assembly 'Octokit, Version=0.28.0.0, Culture=neutral, PublicKeyToken=null' or a dependency couldn't be found. The system could not find the specified file.

**System:**
DCSB v4.0.0.2
Windows 10 Pro 64Bit v1709 Build 16299.192

[Screenshot of Error (german)](https://imgur.com/a/W3TEr)

**Comment by Kalejin** [comment]
Yeah, I forgot to add the library to installer.

**Comment by cyberphobie** [comment]
I just compiled from source and now it is working. Showing "no update available"

**Comment by Kalejin** [comment]
Yes, installer does not take the library from build directory, but when it's built from source it works.
Resolved in commit 6f4451f
