### ISSUE TITLE
Error: Unhandeled exception

### ISSUE THREAD

**Issue by Pakyu1234** [Kalejin/DCSB#128]
![image](https://user-images.githubusercontent.com/109697122/188295047-f98414df-4b83-4ba3-9683-6cab1e08fca8.png)
How do I fix this error? I have restarted my PC multiple times it didn't fix my problem. I've also reinstalled the application to no avail.

**Comment by angrydestreyer9** [comment]
I had a similar issue, are you by any chance using voicemeeter as a mixer?
