### ISSUE TITLE
Won't launch after closing and then reopening. Have to reinstall.

### ISSUE THREAD

**Issue by Dreemlan** [Kalejin/DCSB#14]
I've installed the soundboard and it works, but if I close it and try to launch it again, it doesn't launch.

Attached is the latest crash log.

[DCSB.exe.4220.dmp.zip](https://github.com/Kalejin/DCSB/files/1754793/DCSB.exe.4220.dmp.zip)

**Comment by Kalejin** [comment]
Hi,
Are you sure reinstall helps? Because it seems like your configuration file got corrupted and in that case it should not help.
Can you please attach your configuration file from C:/ProgramData/DCSB/config.xml so I can see what's wrong?

**Comment by Dreemlan** [comment]
By reinstall, I mean I delete every file for the program, including the config file.

I just did some bug testing and the cause of it is adding my "Speakers" as a secondary audio output.

**Comment by Kalejin** [comment]
Yes, then it is probably the same issue as #13

**Comment by Dreemlan** [comment]
Ahh, okay, cool!

I just realized I don't even need to output it to my speakers anyway, but thanks for the response! Love the program.

**Comment by Kalejin** [comment]
Resolved in commit 0c9549e
