### ISSUE TITLE
Can't install it please help!

### ISSUE THREAD

**Issue by ibra851** [Kalejin/DCSB#150]
when i click on it it always says "error launching installer" and I don't know why

**Comment by gandralf83** [comment]
- check if your download isnt corrupted (download again/with other browser)
- right click on the installer file and select "run as administrator"
- check if your windows is up to date
- check if your windows needs repair: open cmd.exe as administrator, type "sfc /scannow" and press enter (this could take a while)

hope it helps, good luck!

**Comment by ibra851** [comment]
I downloaded it from Microsoft edge and it did work!
thank you so much.
