### ISSUE TITLE
Cannot use keybinds or bind any keys when using a Corsair keyboard

### ISSUE THREAD

**Issue by Kaydax** [Kalejin/DCSB#19]
I have a corsair keyboard, and it worked great with this program, even before the 4.X updates, but now it just randomly stopped working when I have my keyboard on normal mode and not bios compatibility, even if I run DCSB as admin.

**Comment by Kalejin** [comment]
Hi,
does DCSB crash or just the key recognition stops working? How much time does it take to stop working? Does restarting program help?
Unfortunately I don't have Corsair keyboard, but I'll try to investigate this

**Comment by Kaydax** [comment]
It doesn't crash, but the keys are not being recognized by the program. It doesn't take any time for the problem to start as it just does it when I open the program

**Comment by Kalejin** [comment]
What exact Corsair keyboard do you use?
Could you please try if version 4.0.0.1 works?

**Comment by Kaydax** [comment]
It seems to be working now after 4.0.0.8, but it seemed to be also an issue of USB drivers, but I cannot confirm this.
