### ISSUE TITLE
Latest windows update, app freezes and won't load

### ISSUE THREAD

**Issue by mikec83** [Kalejin/DCSB#23]
Hi, I am not sure best way to help diagnose this, but with the most recent windows update the app won't run or launch.  I've tried reinstalling it from scratch to no avail.

**Comment by Kalejin** [comment]
Hi,
are you using the newest version 4.0.0.8? It fixes startup issue for some people and even if it crashes it should display information about crash that should help to identify the problem.

**Comment by mikec83** [comment]
Yes I am.  What can I provide to help determine why it is refusing to start?

**Comment by Kalejin** [comment]
Doesn't it display dialog with error message when you try to run it?

**Comment by mikec83** [comment]
No it doesn't.

**Comment by SimonGhoul** [comment]
Older versions do work (3.9.5.2), I guess that helps

**Comment by Kalejin** [comment]
This should be fixed in version 4.0.0.9.
