### ISSUE TITLE
slow and unresponsive 

### ISSUE THREAD

**Issue by Exoriz** [Kalejin/DCSB#24]
After installing the latest release v4.0.0.8 the program is a bit unresponsive,
opening settings takes a few seconds and same goes with starting a sound.

Before updating everything was super fast and sound played instantly.

I have tried uninstalling and installing older versions but that does not help.
I was going to delete the appdata/roaming/deathcounter folder but it appears the settings are stored somewhere else now ?

**Comment by Exoriz** [comment]
Looked everywhere except there,Thanks!

Had hoped deleting the config would fix the unresponsive problem but sadly it did not help

**Comment by Bestest-Coder** [comment]
Yeah I'm having this same issue, there's at least a second long delay between triggering a sound and it happening, it doesn't happen with any other program or audio, just this

**Comment by Glaived** [comment]
I tested version 4.0.0.0.1, and it is not slow.

**Comment by inspiredtolive** [comment]
I am having a similar problem on v4.0.0.8.
There is about a 2-3 second delay between my hotkey press and the actual sound playing.

**Comment by talentedmrripley** [comment]
I was also having problems with 4.0.0.6 being slow.  Going to 4.0.0.3 resolved the issue and playback is instantaneous.

**Comment by Kalejin** [comment]
This should be fixed in version 4.0.0.9.
