### ISSUE TITLE
Error 4.0.0.8

### ISSUE THREAD

**Issue by Lunel3829** [Kalejin/DCSB#25]
Hello,
After a few times using this program, I couldn't seem to launch it.
When using 4.0.0.8, I have this displayed :
![error dcsb](https://user-images.githubusercontent.com/41396336/43983952-b929d8ba-9cfd-11e8-863d-3647f66ed895.png)
If you have any idea how to solve this issue, thanks in advance.

**Comment by mockingbeard** [comment]
I'd appreciate feedback on this as well, I'm having the same issue.

**Comment by ToweringIowa22** [comment]
Same

**Comment by AtomicBrick** [comment]
same

**Comment by BrookletHillGaming** [comment]
same here

**Comment by Kalejin** [comment]
This should be fixed in version 4.0.0.9.
