### ISSUE TITLE
Crash on startup while enumerating devices

### ISSUE THREAD

**Issue by Beanalby** [Kalejin/DCSB#27]
On startup I'm getting:
![unhandledexception](https://user-images.githubusercontent.com/2023094/50746535-8490f000-11fd-11e9-9f06-859f4a2f07ff.png)

Verified it's still happening in source.  Turns out while enumerating my devices one of them comes back with the description "\u0001\\", which RegistryAccess.cs:GetDeviceKey() tries to blindly Substring(4) on.

![debugging](https://user-images.githubusercontent.com/2023094/50746626-f406df80-11fd-11e9-9568-696fdb5bc113.png)

NO IDEA why one of my devices has that name.

For this problem, I changed RegistryAccess.cs:GetDeviceKey() to return null if device.length < 4 before substringing it, and changed Win32.cs:GetDeviceDescription() to pass along the null, and made EnumerateDevices continue to the next loop if it gets back null from GetDeviceDescription (and did the same for DeviceAudit().  That let it work for me.

**Comment by Muzza22** [comment]
Any simple fix as im unsure about what you put on the message above

**Comment by Kalejin** [comment]
This should be fixed in version 4.0.0.9.
