### ISSUE TITLE
v4.0.0.8 rebinding hotkey throws exception error

### ISSUE THREAD

**Issue by GTaichou** [Kalejin/DCSB#29]
I was able to download, install the program, and start setting up a counter. However, when I tried to rebind the "add interval" hotkey to + on the number pad, the program threw an exception error. I now receive this error every time I try to open the program, even after uninstalling and reinstalling, and restarting the PC.

Unfortunately, this is beyond me to solve on my own. Thankfully my other programs seem to be working fine.

![image](https://user-images.githubusercontent.com/48738509/54648977-4d00b880-4a76-11e9-8021-f5680f14204e.png)

**Comment by loststone2** [comment]
I reviving same error happened after my PC hard shut down while using the soundboard I tried uninstalling and reinstalling but didn't fix the issue.
![sdadssa](https://user-images.githubusercontent.com/19869342/56074233-a78eeb00-5d7c-11e9-9050-78dae80392bb.png)

**Comment by firestorm185** [comment]
I think I had a similar issue. After trying it for the first time and then leaving it open for about an hour, trying to do anything with the program resulted in nothing, no sounds, and restarting the app caused this exception - 
![error](https://user-images.githubusercontent.com/12396056/58673440-609f8980-8319-11e9-89df-158fc310cca6.PNG)

**Comment by Kalejin** [comment]
This should be fixed in version 4.0.0.9.
