### ISSUE TITLE
Program won't even start

### ISSUE THREAD

**Issue by amelius1005** [Kalejin/DCSB#30]
I have used this program for the past few months. It has been exactly what I was looking for. The only issue is that as of the past week, the program won't start. I have uninstalled and reinstalled 4 times. I am not very tech savvy, so I'm not even sure how to troubleshoot this issue.  I thank you in advance for your assistance.
![K0UPsb5](https://user-images.githubusercontent.com/48940206/54975345-074f5e80-4f54-11e9-9c00-193fd57448ad.png)

**Comment by Zilronman** [comment]
I have recently been having a similar issue. I see Windows Problem Reporting pop up in the task manager, and when I check the most recent application-based logs in Event Viewer, it seems that the program is opening and then immediately crashing for one reason or another.

A common thread for some of these events is this log:
Fault bucket 1725140037146561743, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: DCSB.exe
P2: 4.0.0.3
P3: 5a79b702
P4: System.Xml
P5: 4.7.3056.0
P6: 5a8e5a09
P7: b85
P8: 27
P9: System.Xml.XmlException
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WEREEB.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER10C1.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER10D2.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER10DC.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1169.tmp.txt

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_DCSB.exe_95e1ca1e996d252aafcc7c7cff15b882f6ff5cb_9a953ecd_323d139f

Analysis symbol: 
Rechecking for solution: 0
Report Id: c16956c8-e594-4840-805b-5144d47856ab
Report Status: 268435456
Hashed bucket: 248bca978f0e5fb2c7f0edb93deccccf
Cab Guid: 0

I have attached the mentioned file in a .Zip file, as it is .Wer file that is unsupported for attaching.
[Report.zip](https://github.com/Kalejin/DCSB/files/3050539/Report.zip)

**Comment by Zilronman** [comment]
After writing my previous comment, I realized I was on version 4.0.0.3. I have since uninstalled it and any other older versions of the software I had on my computer, and installed the most recent version as of now (4.0.0.8). This time it does provide an error message when it fails to launch, which I have attached as a JPG as windows will not let me copy&paste the text from the error window.

While installing the program, I am installing it to the default folder it selects upon running the setup wizard - C:\Program Files (x86)\Deathcounter and Soundboard 

![DCSB unhandled exception error message](https://user-images.githubusercontent.com/49342764/55670573-6d38c180-5843-11e9-8fd4-7e9c9b52770b.png)

**Comment by Muzza22** [comment]
I am currently having the same problem , please let me know if you found a fix

**Comment by fadedacr** [comment]
same

**Comment by Bonkaholic** [comment]
Having the same issue as of yesterday

**Comment by skyler0105** [comment]
Yeah, it seems that the latest windows update completely broke this soundboard, real shame to be honest, its by far one of the best ones out there.  Easy to use, sound overlapping, multiple audio outputs, clean UI, I really hope its fixed.

**Comment by skyler0105** [comment]
![2019-06-14 (2)](https://user-images.githubusercontent.com/51824518/59509593-7ff0f780-8e7f-11e9-88d8-f4d79803cae4.png)

**Comment by ToweringIowa22** [comment]
I also have this issue

**Comment by skyler0105** [comment]
Now, I might be wrong, but I think the developer for this used to have a contact email where you could reach him in a readme, im going to look for it tomorrow, but if anyone else could try and see if they could get this program to work or contact the Dev, it would be greatly appreciated

**Comment by Bonkaholic** [comment]
Update, I tried again today and the program is working again for me

**Comment by ToweringIowa22** [comment]
not for me

**Comment by Zilronman** [comment]
Recently tested this out again, and the program is still not working for me.

It throws out the exact same issue in Safe Mode, which means there are no other third party programs causing an issue with it - the program is having an issue with Windows itself. perhaps a setting or permission out of place?

**Comment by skyler0105** [comment]
I wasn't able to find the email but it is working for me again, I guess make sure you system is updated and uninstall, reinstall it several times , restart your computer, unplug it for a day?  That's pretty much what I did, but I may have just gotten lucky

**Comment by jimmydeanbre** [comment]
i was getting the same error message after DCSB was working fine for a couple months. windows update fixed it for me

**Comment by AtomicBrick** [comment]
the same as Zilronman

**Comment by Bardoogle** [comment]
If you don't mind having to remake your entire soundboard, I've gone to ProgramData to just pretty much delete the DCSB file to get it working again. You can save the configurations for the "config" file within it just in case this happens again so you don't have to delete the entire thing. I've no other idea how to fix it ._.

**Comment by Kalejin** [comment]
This should be fixed in version 4.0.0.9.
