### ISSUE TITLE
Unhandled execption

### ISSUE THREAD

**Issue by KaueGamer7765** [Kalejin/DCSB#36]
#34 
![Sem título](https://user-images.githubusercontent.com/55243871/64789474-d0452780-d54a-11e9-9bec-cdefeeddea59.png) In the image above, it looks like DCSB hears an error, but that's what happens in versions 4.0.0.1 through 4.0.0.6 in those versions, the error and this 
![Sem título2](https://user-images.githubusercontent.com/55243871/64789568-f8cd2180-d54a-11e9-94c6-9b368334b56c.png) this other photo appears in versions 4.0.0.7 and 4.0.0.8 now it helps me me this error appeared out of nowhere when i turned on the pc and appeared on the screen when i started the program

**Comment by Kalejin** [comment]
This should be fixed in version 4.0.0.9.
