### ISSUE TITLE
Presets import

### ISSUE THREAD

**Issue by ImmRanneft** [Kalejin/DCSB#37]
He there. Where can I find presets so I can import them to another PC?

**Comment by ImmRanneft** [comment]
NVM, found it. Sry for disturbing you.

**Comment by ginqus** [comment]
@ImmRanneft Hi, do you still know where it is? I'm trying to import them as well, sorry if i'm distracting you

**Comment by ginqus** [comment]
nvm, found it here: "C:\ProgramData\DCSB"
