### ISSUE TITLE
Wont open

### ISSUE THREAD

**Issue by ARandomSqueaker** [Kalejin/DCSB#39]
So 1-2 days ago, I reset my pc and installed DCSB. It worked, then later on, i reopened it and it said this[]
![a](https://user-images.githubusercontent.com/28767406/67652161-feb37200-f900-11e9-8361-3f1e73b85a68.png)
(url)

**Comment by ARandomSqueaker** [comment]
Fixed
Did this
https://prnt.sc/q1746m

To get the programdata
WINDOWS+R
then type
%ProgramData%

**Comment by Kalejin** [comment]
This should be fixed in version 4.0.0.9.
