### ISSUE TITLE
Not Compatible with Windows 10

### ISSUE THREAD

**Issue by H3rbe** [Kalejin/DCSB#41]
The latest Windows 10 update appears to have broken the soundboard completely. It is unable to launch now and only shows unhandled expressions. I tried troubleshooting it but it's completely incompatible. Seeing the ammount of unsolved issues, I doubt this is active which is quite unfortunate as I really loved this soundboard. I hope you are able to fix this or at the very least provide us with an answer.

Thanks.
![unhandled expession](https://user-images.githubusercontent.com/60243835/73034444-c6d1a300-3df9-11ea-8d3e-c36e391a17bf.jpg)

**Comment by brendanteske** [comment]
Add one to that, please. I use this when playing Overwatch for a death counter (Wins/Loss/Draw). If this gets fixed I'd be so happy.

**Comment by audelaney** [comment]
Have you tried this recently? Seems to run for me from VS2019

**Comment by SrPeterr** [comment]
Same here, yesterday was working perfect, today I get the same error

**Comment by Kalejin** [comment]
This should be fixed in version 4.0.0.9.
