### ISSUE TITLE
This is the issue I am having. Someone please help- it worked fine one day and the next it quit

### ISSUE THREAD

**Issue by BrookletHillGaming** [Kalejin/DCSB#43]
![image](https://user-images.githubusercontent.com/61436057/75194355-f68c0780-5725-11ea-9039-e08372b99942.png)
It was working fine  last week but i tried to use it over the weekend and it gave me this error and NOTHING is working not even running as admin

**Comment by Kalejin** [comment]
This should be fixed in version 4.0.0.9.
