### ISSUE TITLE
Software freezes for a few seconds every time a sound is played

### ISSUE THREAD

**Issue by Ezzocorbi** [Kalejin/DCSB#44]
I'm using version 4.0.0.8

Whenever I play a sound, the software freezes for a few seconds.
Also when I click on the "Settings" button, the program freezes for about 15 seconds before opening the settings window.

This makes the whole program unusable, I hope it gets fixed soon as I love this software and I think it's the best soundboard available for free.

**Comment by Kalejin** [comment]
This should be fixed in version 4.0.0.9.
