### ISSUE TITLE
Unhandled exception System.IndexOutOfRangeException

### ISSUE THREAD

**Issue by Marko420HR** [Kalejin/DCSB#45]
Just booted up my pc and got this when DCSB autostarted 
![desktop](https://user-images.githubusercontent.com/31570481/76845199-c88a7680-683e-11ea-8b25-95fb1fe25e26.png)

**Comment by ZeAnooky** [comment]
I'm receiving the exact same exception. This error occurs so often for me now. The app may work about 30% of the time for me. One day, it opens perfectly fine. For the next week, I'll be thrown this exception. I have DCSB 4.0.0.8 installed on my Windows 10 laptop.

**Comment by Marko420HR** [comment]
It happens when I boot up with my Oculus Rift connected

**Comment by gggghhhejehdhdhdhdhh** [comment]
Anyone find it out yet

**Comment by Kalejin** [comment]
This should be fixed in version 4.0.0.9.
