### ISSUE TITLE
Issue after computer crash

### ISSUE THREAD

**Issue by phenyx310** [Kalejin/DCSB#46]
My computer crashed during streaming and when it restarted I had this screen when i opened the program. I do believe it is DCSB_4.0.0.8
![Screenshot (32)](https://user-images.githubusercontent.com/62409629/77128639-3396a180-6a27-11ea-9b3c-3de2b382e9fb.png)

I've tried uninstalling and reinstalling. I've tried older versions and nothing seems to work. When I download older versions, they just don't open.

**Comment by Kici33** [comment]
Go to C:\ProgramData\DCSB and remove config.xml
It got corupted after computer crash, enjoy !

**Comment by Kalejin** [comment]
This should be fixed in version 4.0.0.9.
