### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by Kici33** [Kalejin/DCSB#52]
Hello, as I saw that you didn't abort the project I want to give my feedback.

Recently I found a bug (I think it is)
When you are adding new sound that contains buttons from others (e.g. Alt+Num3) and you want to create sound on (Alt+Ctrl+Num3), it will automatically play Alt+Num3 sound.

Steps to reproduce
1. (setup sound)
2. (add sound with aditional combination that contains combination from existing sound)

I really enjoy your project and I'm glad that you are updating it. Stay Strong !

**Comment by Kalejin** [comment]
Hi! 
Nice catch and very well written. I'll take a look at it.
Thanks

**Comment by Kici33** [comment]
I also found something, that when you're adding sounds, and you are adding next combination there is a chance that it'll replace the actual song without something from that combination.

**Comment by Kalejin** [comment]
Yes, the fix I have ready is going to solve that as well. Thank you.
