### ISSUE TITLE
Virus?

### ISSUE THREAD

**Issue by Yoyoenter** [Kalejin/DCSB#60]
My windows security is telling me that this download and hurt my PC, can anyone tell if it's safe to download or run

**Comment by Thijmenz** [comment]
Norton says it's save and I didn't experience something strange about the programm

**Comment by jessemillar** [comment]
I think it's just not signed with a certificate that Windows recognizes.

**Comment by Barkeeper-123** [comment]
https://www.virustotal.com/gui/file/d39db773d0d16d73e170e4f7a0c5fe2ebe4c93ab605a36f52ff3fb2d0f4b7104/detection
I dont think its a virus
But if you wanna be sure rather dont download it

**Comment by CamiloBroermann** [comment]
> 
> 
> https://www.virustotal.com/gui/file/d39db773d0d16d73e170e4f7a0c5fe2ebe4c93ab605a36f52ff3fb2d0f4b7104/detection
> I dont think its a virus
> But if you wanna be sure rather dont download it

Why do you think it is not a Virus, if 7 Companys from your url say it has some Malware?

**Comment by ITCMD** [comment]
The way virus detectors work is by detecting snippets of code that perform actions. In some cases, these actions are be expected and simply part of the program. For example, I made a project that downloaded files from a website it was monitoring. Some antiviruses detected this as a virus, as some viruses will download files containing malicious code to run.

In any case, DCSB is open source, so you can look at the code and compile it yourself. Then, compare it to the release. As long as they are identical, you know it's not malicious.

7 (now 6) detections on virustotal isn't bad at all. It means that most antiviruses agree that its not a virus. You'll be hard-pressed to find a program that doesn't trigger some of them.

**Comment by ITCMD** [comment]
Is this something you would be willing to close @Yoyoenter?

**Comment by Yoyoenter** [comment]
What? Who are you? And close what

**Comment by ITCMD** [comment]
I'm just another person on Github like you. And close the issue since it has been explained to you why this isn't a virus.

Next the the comment button you should see the "close" button. :P
