### ISSUE TITLE
No longer letting me use Virtual Audio Cable as Output Device

### ISSUE THREAD

**Issue by Bonyoze** [Kalejin/DCSB#68]
Was working fine yesterday, but today I received an error upon trying to start the program. Reinstalling the program fixed it, but now I am unable to set the VB-Audio Virtual Cable as an Output Device. It will always reset back to what it originally had when I view the Settings again.

The version I'm using is 4.0.0.9.

**Comment by Bonyoze** [comment]
![Untitled](https://user-images.githubusercontent.com/59924045/90322828-122ed880-df27-11ea-9f63-f0ed32672212.png)
A red dot appears on the sounds I play when I try to select the VB-Audio Virtual Cable. This is the error

**Comment by Bonyoze** [comment]
Fixed

**Comment by evan-william** [comment]
how did u fix it , i had the same problem
